name: hotspot_cards
description: تطبيق بائع الكروت لإدارة وبيع كروت الإنترنت.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  csv: ^6.0.0

  file_picker: ^10.3.3

  path_provider: ^2.1.5

  receive_sharing_intent: ^1.8.1

  share_plus: ^12.0.0

  shared_preferences: ^2.5.3

  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon/ic_launcher.png